# Generated by Django 3.1 on 2021-09-03 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210902_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='nio',
            name='dat',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
